export const ftDummyListData = [
  {
    truckId: "175204",
    name: "오남 핫도그",
    category: "간식",
    like: true,
    review: [
      { nickName: "핫도그매니아", content: "치즈가 쭉 늘어나서 좋아요.", rating: 4.0 },
      { nickName: "감자덕후", content: "감자핫도그가 바삭해요!", rating: 4.5 },
    ],
    intro: "겉은 바삭, 속은 촉촉한 수제 핫도그를 맛볼 수 있습니다.",
    menu: [
      { name: "치즈핫도그", price: "3000", info: "쭉 늘어나는 치즈", num: "1" },
      { name: "감자핫도그", price: "3500", info: "감자가 듬뿍", num: "2" },
    ],
    schedule: [
      {
        day: "월",
        holiday: false,
        start: "12",
        end: "20",
        mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
        userAddress: "오남초등학교 앞",
        sms: false,
      },
      {
        day: "화",
        holiday: true,
        start: "12",
        end: "20",
        mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
        userAddress: "오남초등학교 앞",
        sms: true,
      },
      {
        day: "수",
        holiday: false,
        start: "12",
        end: "20",
        mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
        userAddress: "오남초등학교 앞",
        sms: false,
      },
      {
        day: "목",
        holiday: true,
        start: "12",
        end: "20",
        mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
        userAddress: "오남초등학교 앞",
        sms: true,
      },
      {
        day: "금",
        holiday: true,
        start: "12",
        end: "20",
        mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
        userAddress: "오남초등학교 앞",
        sms: true,
      },
      {
        day: "토",
        holiday: true,
        start: "12",
        end: "20",
        mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
        userAddress: "오남초등학교 앞",
        sms: true,
      },
      {
        day: "일",
        holiday: true,
        start: "12",
        end: "20",
        mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
        userAddress: "오남초등학교 앞",
        sms: true,
      },
    ],
  },
  {
    truckId: "357902",
    name: "오남 군고구마",
    category: "간식",
    like: false,
    review: [
      { nickName: "고구마매니아", content: "군고구마가 달콤하고 촉촉해요.", rating: 4.5 },
      { nickName: "겨울간식러", content: "겨울에 딱이에요!", rating: 4.0 },
    ],
    intro: "겨울철 인기 간식, 따끈한 군고구마를 판매합니다.",
    menu: [{ name: "군고구마", price: "3000", info: "달콤하고 촉촉한 고구마", num: "1" }],
    schedule: [
      { day: "월", holiday: true, start: "14", end: "20", mapAddress: "경기 남양주시 오남읍 진건오남로555번길 19", userAddress: "오남공원 입구" },
      { day: "화", holiday: true, start: "14", end: "20", mapAddress: "경기 남양주시 오남읍 진건오남로555번길 19", userAddress: "오남공원 입구" },
      { day: "수", holiday: true, start: "14", end: "20", mapAddress: "경기 남양주시 오남읍 진건오남로555번길 19", userAddress: "오남공원 입구" },
      { day: "목", holiday: true, start: "14", end: "20", mapAddress: "경기 남양주시 오남읍 진건오남로555번길 19", userAddress: "오남공원 입구" },
      { day: "금", holiday: false, start: "14", end: "20", mapAddress: "경기 남양주시 오남읍 진건오남로555번길 19", userAddress: "오남공원 입구" },
      { day: "토", holiday: false, start: "14", end: "20", mapAddress: "경기 남양주시 오남읍 진건오남로555번길 19", userAddress: "오남공원 입구" },
      { day: "일", holiday: false, start: "14", end: "20", mapAddress: "경기 남양주시 오남읍 진건오남로555번길 19", userAddress: "오남공원 입구" },
    ],
  },
  {
    truckId: "930217",
    name: "진건 떡볶이",
    category: "분식",
    like: false,
    review: [
      { nickName: "떡볶이짱", content: "매콤달콤해서 자주 먹어요.", rating: 5.0 },
      { nickName: "튀김러버", content: "튀김이 바삭해요.", rating: 4.5 },
    ],
    intro: "매콤달콤한 떡볶이와 다양한 튀김을 판매합니다.",
    menu: [
      { name: "떡볶이", price: "4000", info: "쫄깃한 떡과 매콤한 소스", num: "1" },
      { name: "오뎅", price: "1000", info: "따끈한 국물 오뎅", num: "2" },
    ],
    schedule: [
      { day: "월", holiday: true, start: "11", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 522 1층", userAddress: "진건시장 입구" },
      { day: "화", holiday: false, start: "11", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 522 1층", userAddress: "진건시장 입구" },
      { day: "수", holiday: false, start: "11", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 522 1층", userAddress: "진건시장 입구" },
      { day: "목", holiday: false, start: "11", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 522 1층", userAddress: "진건시장 입구" },
      { day: "금", holiday: false, start: "11", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 522 1층", userAddress: "진건시장 입구" },
      { day: "토", holiday: false, start: "11", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 522 1층", userAddress: "진건시장 입구" },
      { day: "일", holiday: false, start: "11", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 522 1층", userAddress: "진건시장 입구" },
    ],
  },
  {
    truckId: "604381",
    name: "오남 닭꼬치",
    category: "구이",
    like: false,
    review: [
      { nickName: "닭꼬치러버", content: "불향이 진짜 좋아요!", rating: 4.5 },
      { nickName: "소스장인", content: "소스가 다양해서 골라먹는 재미가 있어요.", rating: 4.0 },
    ],
    intro: "불향 가득한 닭꼬치와 다양한 소스를 즐길 수 있습니다.",
    menu: [
      { name: "매운닭꼬치", price: "3500", info: "매콤한 소스", num: "1" },
      { name: "간장닭꼬치", price: "3500", info: "달콤한 간장소스", num: "2" },
    ],
    schedule: [
      { day: "월", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "오남역 2번 출구 앞" },
      { day: "화", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "오남역 2번 출구 앞" },
      { day: "수", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "오남역 2번 출구 앞" },
      { day: "목", holiday: false, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "오남역 2번 출구 앞" },
      { day: "금", holiday: false, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "오남역 2번 출구 앞" },
      { day: "토", holiday: false, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "오남역 2번 출구 앞" },
      { day: "일", holiday: false, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "오남역 2번 출구 앞" },
    ],
  },
  {
    truckId: "218765",
    name: "진건 크레페",
    category: "디저트",
    like: false,
    review: [
      { nickName: "디저트홀릭", content: "딸기크레페가 상큼해요.", rating: 4.5 },
      { nickName: "초코러버", content: "바나나크레페도 맛있어요!", rating: 4.0 },
    ],
    intro: "달콤한 크레페와 신선한 과일 토핑을 제공합니다.",
    menu: [
      { name: "딸기크레페", price: "5000", info: "딸기와 생크림", num: "1" },
      { name: "바나나크레페", price: "5000", info: "바나나와 초코", num: "2" },
    ],
    schedule: [
      { day: "월", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 529-2", userAddress: "진건도서관 앞" },
      { day: "화", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 529-2", userAddress: "진건도서관 앞" },
      { day: "수", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 529-2", userAddress: "진건도서관 앞" },
      { day: "목", holiday: false, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 529-2", userAddress: "진건도서관 앞" },
      { day: "금", holiday: false, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 529-2", userAddress: "진건도서관 앞" },
      { day: "토", holiday: false, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 529-2", userAddress: "진건도서관 앞" },
      { day: "일", holiday: false, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 진건오남로 529-2", userAddress: "진건도서관 앞" },
    ],
  },
  {
    truckId: "482913",
    name: "황금 잉어빵",
    category: "간식",
    like: false,
    review: [
      { nickName: "맛집러", content: "붕어빵이 정말 맛있어요!", rating: 4.5 },
      { nickName: "간식왕", content: "슈크림이 듬뿍 들어있어요.", rating: 5.0 },
    ],
    intro: "신선한 재료로 만든 달콤한 붕어빵을 판매합니다. 남녀노소 모두 좋아하는 간식입니다.",
    menu: [
      { name: "팥붕어빵", price: "2000", info: "팥이 듬뿍 들어간 붕어빵", num: "1" },
      { name: "슈크림붕어빵", price: "2500", info: "부드러운 슈크림이 가득", num: "2" },
    ],
    schedule: [
      { day: "월", holiday: false, start: "15", end: "21", mapAddress: "경기도 남양주시 진건오남로 516-53", userAddress: "진건역 1번 출구 앞" },
      { day: "화", holiday: false, start: "15", end: "21", mapAddress: "경기도 남양주시 진건오남로 516-53", userAddress: "진건역 1번 출구 앞" },
      { day: "수", holiday: true, start: "15", end: "21", mapAddress: "경기도 남양주시 진건오남로 516-53", userAddress: "진건역 1번 출구 앞" },
      { day: "목", holiday: true, start: "15", end: "21", mapAddress: "경기도 남양주시 진건오남로 516-53", userAddress: "진건역 1번 출구 앞" },
      { day: "금", holiday: true, start: "15", end: "21", mapAddress: "경기도 남양주시 진건오남로 516-53", userAddress: "진건역 1번 출구 앞" },
      { day: "토", holiday: true, start: "15", end: "21", mapAddress: "경기도 남양주시 진건오남로 516-53", userAddress: "진건역 1번 출구 앞" },
      { day: "일", holiday: true, start: "15", end: "21", mapAddress: "경기도 남양주시 진건오남로 516-53", userAddress: "진건역 1번 출구 앞" },
    ],
  },

  {
    truckId: "809134",
    name: "진건 아이스크림",
    category: "디저트",
    review: [
      { nickName: "아이스크림러버", content: "바닐라맛이 진해요.", rating: 4.5 },
      { nickName: "토핑덕후", content: "토핑이 다양해서 좋아요.", rating: 4.0 },
    ],
    like: true,
    intro: "다양한 맛의 아이스크림과 토핑을 즐길 수 있습니다.",
    menu: [
      { name: "바닐라", price: "2500", info: "기본 바닐라맛", num: "1" },
      { name: "초코", price: "2500", info: "진한 초코맛", num: "2" },
    ],
    schedule: [
      { day: "월", holiday: true, start: "12", end: "18", sms: true, mapAddress: "경기 남양주시 오남읍 양지로 57", userAddress: "진건초등학교 앞" },
      { day: "화", holiday: true, start: "12", end: "18", sms: true, mapAddress: "경기 남양주시 오남읍 양지로 57", userAddress: "진건초등학교 앞" },
      { day: "수", holiday: true, start: "12", end: "18", sms: true, mapAddress: "경기 남양주시 오남읍 양지로 57", userAddress: "진건초등학교 앞" },
      { day: "목", holiday: true, start: "12", end: "18", sms: true, mapAddress: "경기 남양주시 오남읍 양지로 57", userAddress: "진건초등학교 앞" },
      { day: "금", holiday: false, start: "12", end: "18", sms: false, mapAddress: "경기 남양주시 오남읍 양지로 57", userAddress: "진건초등학교 앞" },
      { day: "토", holiday: false, start: "12", end: "18", sms: false, mapAddress: "경기 남양주시 오남읍 양지로 57", userAddress: "진건초등학교 앞" },
      { day: "일", holiday: false, start: "12", end: "18", sms: false, mapAddress: "경기 남양주시 오남읍 양지로 57", userAddress: "진건초등학교 앞" },
    ],
  },

  {
    truckId: "294650",
    name: "진건 소떡소떡",
    category: "간식",
    like: false,
    review: [
      { nickName: "소떡러버", content: "소떡소떡이 쫄깃하고 소스가 맛있어요.", rating: 4.5 },
      { nickName: "매콤단짠", content: "매콤달콤해서 계속 생각나요.", rating: 4.0 },
    ],
    intro: "소시지와 떡이 번갈아 꽂힌 소떡소떡, 매콤달콤한 소스와 함께!",
    menu: [{ name: "소떡소떡", price: "3500", info: "소시지+떡+소스", num: "1" }],
    schedule: [
      { day: "월", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "진건역 2번 출구 앞" },
      { day: "화", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "진건역 2번 출구 앞" },
      { day: "수", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "진건역 2번 출구 앞" },
      { day: "목", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "진건역 2번 출구 앞" },
      { day: "금", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "진건역 2번 출구 앞" },
      { day: "토", holiday: true, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "진건역 2번 출구 앞" },
      { day: "일", holiday: false, start: "16", end: "22", mapAddress: "경기 남양주시 오남읍 양지로125번길 23 2동", userAddress: "진건역 2번 출구 앞" },
    ],
  },
  {
    truckId: "294613",
    name: "오남 옥수수",
    category: "간식",
    like: false,
    review: [
      { nickName: "옥수수매니아", content: "옥수수가 달콤하고 고소해요.", rating: 4.0 },
      { nickName: "간식러버", content: "국산 옥수수라서 믿고 먹어요.", rating: 3.5 },
    ],
    intro: "달콤하고 고소한 찐옥수수를 판매합니다.",
    menu: [{ name: "찐옥수수", price: "2000", info: "국산 옥수수 사용", num: "1" }],
    schedule: [
      { day: "월", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 양지로 121", userAddress: "오남도서관 앞" },
      { day: "화", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 양지로 121", userAddress: "오남도서관 앞" },
      { day: "수", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 양지로 121", userAddress: "오남도서관 앞" },
      { day: "목", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 양지로 121", userAddress: "오남도서관 앞" },
      { day: "금", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 양지로 121", userAddress: "오남도서관 앞" },
      { day: "토", holiday: true, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 양지로 121", userAddress: "오남도서관 앞" },
      { day: "일", holiday: false, start: "13", end: "19", mapAddress: "경기 남양주시 오남읍 양지로 121", userAddress: "오남도서관 앞" },
    ],
  },
  {
    truckId: "561478",
    name: "오남 타코야끼",
    category: "간식",
    like: false,
    review: [
      { nickName: "타코야끼매니아", content: "문어가 쫄깃해요.", rating: 4.0 },
      { nickName: "소스맛집", content: "특제소스가 정말 맛있어요!", rating: 4.5 },
    ],
    intro: "쫄깃한 문어와 특제 소스가 어우러진 타코야끼를 판매합니다.",
    menu: [{ name: "타코야끼", price: "4000", info: "6개입, 특제소스", num: "1" }],
    schedule: [
      { day: "월", holiday: true, start: "15", end: "21", mapAddress: "경기 남양주시 오남읍 양지로81번길 2 1층", userAddress: "오남시장 입구" },
      { day: "화", holiday: true, start: "15", end: "21", mapAddress: "경기 남양주시 오남읍 양지로81번길 2 1층", userAddress: "오남시장 입구" },
      { day: "수", holiday: true, start: "15", end: "21", mapAddress: "경기 남양주시 오남읍 양지로81번길 2 1층", userAddress: "오남시장 입구" },
      { day: "목", holiday: true, start: "15", end: "21", mapAddress: "경기 남양주시 오남읍 양지로81번길 2 1층", userAddress: "오남시장 입구" },
      { day: "금", holiday: true, start: "15", end: "21", mapAddress: "경기 남양주시 오남읍 양지로81번길 2 1층", userAddress: "오남시장 입구" },
      { day: "토", holiday: false, start: "15", end: "21", mapAddress: "경기 남양주시 오남읍 양지로81번길 2 1층", userAddress: "오남시장 입구" },
      { day: "일", holiday: false, start: "15", end: "21", mapAddress: "경기 남양주시 오남읍 양지로81번길 2 1층", userAddress: "오남시장 입구" },
    ],
  },
];
