export const ftDummyData = {
  truckId: "175204",
  name: "오남 핫도그",
  category: "간식",
  review: [
    { nickName: "핫도그매니아", content: "치즈가 쭉 늘어나서 좋아요.", rating: 4.0 },
    { nickName: "감자덕후", content: "감자핫도그가 바삭해요!", rating: 4.5 },
  ],
  intro: "겉은 바삭, 속은 촉촉한 수제 핫도그를 맛볼 수 있습니다.",
  menu: [
    { name: "치즈핫도그", price: "3000", info: "쭉 늘어나는 치즈", num: "1" },
    { name: "감자핫도그", price: "3500", info: "감자가 듬뿍", num: "2" },
  ],
  schedule: [
    {
      day: "월",
      holiday: false,
      start: "12",
      end: "20",
      mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
      userAddress: "오남초등학교 앞",
    },
    {
      day: "화",
      holiday: true,
      start: "12",
      end: "20",
      mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
      userAddress: "오남초등학교 앞",
    },
    {
      day: "수",
      holiday: false,
      start: "12",
      end: "20",
      mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
      userAddress: "오남초등학교 앞",
    },
    {
      day: "목",
      holiday: true,
      start: "12",
      end: "20",
      mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
      userAddress: "오남초등학교 앞",
    },
    {
      day: "금",
      holiday: true,
      start: "12",
      end: "20",
      mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
      userAddress: "오남초등학교 앞",
    },
    {
      day: "토",
      holiday: true,
      start: "12",
      end: "20",
      mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
      userAddress: "오남초등학교 앞",
    },
    {
      day: "일",
      holiday: true,
      start: "12",
      end: "20",
      mapAddress: "경기 남양주시 오남읍 진건오남로522번길 11-1 지산파크빌상가",
      userAddress: "오남초등학교 앞",
    },
  ],
};
